gideon-legal/chatbot

package-lock.json
src/scss/botchat.scss

should remove mwmlaw css bug
* Test for regressions on bugs that our tests did not catch.
* Are needed to harden new features.

Removed all box-shadows on buttons

---

src/scss/botchat.scss

* Test for regressions on bugs that our tests did not catch.
* Are needed to harden new features.

clearfix possible fix for footer

---

src/Chat.tsx
src/Store.ts
src/Types.ts

[GD-339]
[GD-339]: https://gideonlegal.atlassian.net/browse/GD-339

parse, and utilize topOffset from bot_display_options

---

src/DatePickerCard.tsx

Hiding time slots while loading

Added check for end of time slot within availability end time

---

src/Chat.tsx
src/Store.ts

Added fullHeight through props capability. Scroll bar for website should always be visible.

Full height chatbot through props

---

src/History.tsx
src/scss/botchat.scss
src/scss/includes/settings.scss

Lead messages are right aligned now
align avatar to bottom of message
Align avatar to bottom and only show avatar for last sent message from bot within group of messages
Added background color to input, changed width and margins to reduce white space

UI changes based on feedback

---

package-lock.json
package.json
src/ActivityView.tsx
src/ContactFormCard.tsx
src/History.tsx
src/scss/botchat.scss
src/scss/gideon.scss

Basic ContactFormCard being displayed when a contact node_type is received
Basic contact form is working. Phone validation/input is still an issue
removed console.log
Improved phone validation. Verifying it's the correct number of numbers and has valid symbols

Contact Form Card

---

src/DatePickerCard.tsx

Don't convert availability timestamps to UTC

---

src/ActivityView.tsx
src/DatePickerCard.tsx
src/scss/includes/date-picker.scss

Days are being listed dynamically by week, and weeks can be navigated. Initial styling for day selection
Basic functionality is working now
Formatting timestamp when displayed to remove the offset at the end
Reduced header. Adjusted dates to block out
Only display buttons if availabilities exist
Day picker is basically complete. Will model hour picker the same
All styling and functionality is generally done. Waiting on feedback to adjust as needed
Second header is blank now on 'select a day' screen

Updated DatePicker

---

package-lock.json
package.json
src/DatePickerCard.tsx
src/scss/includes/date-picker.scss

Adjusted logic to show current day correctly

Added react-icons and changed back button icon with appropriate styling

---

src/ActivityView.tsx
src/DatePickerCard.tsx
src/scss/includes/date-picker.scss

Functionality updated to accommodate for both handoff and date nodes
date and handoff nodes are both functional and adjusted styling for each.
Fixed issue with number node being formatted as a date

Added functionality to handle both date and handoff

---

package-lock.json
src/Chat.tsx
src/FloatingIcon.tsx
src/Types.ts

[GD-384]
[GD-384]: https://gideonlegal.atlassian.net/browse/GD-384

left align Chat, FloatingIcon via bot display options

---

src/DatePickerCard.tsx
src/DisclaimerCard.tsx
src/History.tsx
src/scss/botchat.scss
src/scss/includes/date-picker.scss

Handle 2 lines of text for date picker buttons
Change wording of input for date picker
Add markdown to disclaimer

Assorted fixes

---

.gitignore
src/Chat.tsx
src/FloatingIcon.tsx
src/Store.ts
src/Types.ts

- Pull in the widget url and use that if available or use the header logo if the user chooses to use that instead.

feat GD-405 - Upload Chatbot Image

---

src/FloatingIcon.tsx

hotfix: Remove conflict markers

---

package-lock.json
package.json
src/Chat.tsx
src/analytics-utils.d.ts
src/api/bot.ts
tsconfig.json

[GD-303]
* Test for regressions on bugs that our tests did not catch.
* Are needed to harden new features.
[GD-303]: https://gideonlegal.atlassian.net/browse/GD-303

parse UTM parms, include in verifyConversation request

---

src/ActivityView.tsx
src/MultipleChoiceCard.tsx
src/scss/includes/multiple-upload.scss

Adds support for multiple selection in multiple choice card.

Production Sample Documents

---

src/Chat.tsx
src/FormattedText.tsx
src/History.tsx
src/Store.ts
src/scss/botchat.scss
src/scss/includes/settings.scss

- When it is a user's first time the botId and orgId were not being sent into the new conversation causing a 400
- Add max height to the back button so that it isn't pushing the header items off center
- Fix logic decided which type of text styling to use when receiving messages

fix: Chatbot feedback

---

package-lock.json
src/ActivityView.tsx
src/Chat.tsx
src/History.tsx
src/PastConversations.tsx
src/RestartPromptCard.tsx
src/Store.ts
src/scss/botchat.scss

- Stop 'start' and 'restart' messages from sending on initial load
- Add a prompt to the user to select to continue current conversation or start a new one
- Push the user into their most recent conversation when they first load

feat: Restart Node

---

src/Chat.tsx
src/scss/botchat.scss

- Update the styles for the header so that they look better in staging

fix: GD-457 - Chatbot Header

---

src/AddressFormCard.tsx
src/scss/botchat.scss

removed logs
Hide components when entering a different address in the main input. Also handle keydown in secondary address field
Removed unnecessary comment

General functionality and styling for components

---

src/Chat.tsx

- Handle case where new user does not respond to the first message, resulting in the user to not have any valid conversations when they revisit the page

fix: General Conversation Bugs

---

src/AddressFormCard.tsx
src/scss/botchat.scss

Auto focus Unit/Apartment text box
Add styling to prevent text wrapping to multiple lines
Styling to mimic google maps

Additional changes for address form

---

src/Chat.tsx
src/History.tsx
src/api/bot.ts

- Only fetch past conversations for the current bot

fix: Final History Updates

---

src/Chat.tsx
src/History.tsx
src/Shell.tsx
src/Store.ts
src/Types.ts
src/scss/botchat.scss

Sbu fullscreen

---

src/FileUploadCard.tsx
src/SubmitButton.tsx
src/scss/botchat.scss
src/scss/includes/file-upload.scss

For use with dome of the other chat widgets

Resuable submit button

---

src/DatePickerCard.tsx
src/History.tsx
src/assets/icons/DatePickerIcons.tsx
src/scss/botchat.scss
src/scss/includes/date-picker.scss

- New floating calendar in node supporting various screen sizes

Sbu calendar updates

---

src/DisclaimerCard.tsx
src/DisclaimerCardReadOnly.tsx
src/History.tsx
src/scss/botchat.scss

- Max disclaimer height
- Scrollable disclaimer
- Grey background disclaimer
- No message from bot upon disclaimer
- Width s now bigger than other nodes
- Button heights adjusted to match Figma
- Fixed spacing between multiple buttons

GD-610 Disclaimer updates

---

src/DatePickerCard.tsx
src/SubmitButton.tsx
src/scss/botchat.scss
src/scss/includes/date-picker.scss

- Disclaimer node has an equal amount of space on left and right
- The header for calendar node matches other nodes
- Calendar header text changed from “Date Picker” to “Select Date”
- Calendar submit button matches those of the other nodes
- Contact node prefixes fits on one line on mobile devices now

Sbu disclaimer, calendar, and address node updates

---

src/AddressCard.tsx
src/scss/botchat.scss

- Floating dropdown for address node
- Closed Chatbot message show up on left of icon
- Closed Chatbot messages are styled like open Chatbot messages
- Tooltip on closed Chatbot messages

Sbu joey sprint 40

---

src/Chat.tsx
src/Types.ts

no idea why prod refuses to accept fullHeight as a member of FormatOptions

FormatOptions fullHeight changed to full_height

---

src/Chat.tsx

Reverts gideon-legal/chatbot#172

Revert "Sbu convoID storage & check"

---

src/Chat.tsx
src/ConversationHistory.tsx

-treating back button as the current convo within the list 
-fixing history list

history page & back current convo

---

src/Chat.tsx

Reverts gideon-legal/chatbot#188

Revert "Sbu backbutton slowness"

---

src/Chat.tsx
src/History.tsx

-fix completed convo view
-fix loading page
-fix reload after new convo prompt clicked (session storage)

fixes for staging

---

src/Chat.tsx

Reverts gideon-legal/chatbot#212

Revert "Sbu history limit - fix for blank issue"

---

src/Chat.tsx

Reverts gideon-legal/chatbot#233

Revert "Added cases to check for activity length and entities"

---

src/Chat.tsx

Added more cases in else for typing and message activities

Modified handleIncomingActivty to check for entites + node type

---

src/Chat.tsx

Reverts gideon-legal/chatbot#242

Revert "Sbu backbutton count"

---

src/VideoCard.tsx

Saas video work

---

src/DatePickerCard.tsx

Adjusted year selection on calendar
